Repository OpenMined/Threepio, pull requests merged in 2020-01, with the labels that each got.

#9 Fix torch urls
  docs-crawler/docs/docs/spiders/torch_spider.py
  docs-crawler/docs/output/torch/1.4.0.json
Labels: improvement

#6 Initial scaffolding for javascript package
  .editorconfig
  .gitattributes
  .gitignore
  .remarkignore
  .travis.yml
  LICENSE
  README.md
  index.js
  package-lock.json
  package.json
  rollup.config.js
  test/test.js
Labels: enhancement, needs review

#13 fix: switch rollup package to fix security vuln
  package-lock.json
  package.json
Labels: needs review
